import type { Config } from "tailwindcss"

const config: Config = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#e0b6ff",
        "on-tertiary-fixed-variant": "#6a0baa",
        "surface-container": "#eaedff",
        "primary-fixed-dim": "#b0c6ff",
        "on-tertiary-container": "#fffbff",
        "surface-bright": "#faf8ff",
        "primary-fixed": "#d9e2ff",
        "on-primary-fixed-variant": "#00429c",
        "on-secondary-fixed-variant": "#38485d",
        error: "#ba1a1a",
        "inverse-surface": "#283044",
        "on-tertiary": "#ffffff",
        surface: "#faf8ff",
        background: "#faf8ff",
        "secondary-fixed-dim": "#b7c8e1",
        "inverse-on-surface": "#eef0ff",
        "tertiary-fixed": "#f2daff",
        "on-surface-variant": "#424655",
        "primary-container": "#006df8",
        "on-secondary-container": "#54647a",
        "surface-variant": "#dae2fd",
        "surface-container-highest": "#dae2fd",
        "surface-dim": "#d2d9f4",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "tertiary-container": "#9c4ddc",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "on-background": "#131b2e",
        secondary: "#505f76",
        "on-error": "#ffffff",
        tertiary: "#8130c1",
        outline: "#727787",
        "on-primary": "#ffffff",
        "surface-tint": "#0058cb",
        "secondary-container": "#d0e1fb",
        "on-primary-container": "#fefcff",
        "on-primary-fixed": "#001945",
        "on-tertiary-fixed": "#2e004e",
        primary: "#0056c6",
        "outline-variant": "#c2c6d8",
        "surface-container-high": "#e2e7ff",
        "on-surface": "#131b2e",
        "inverse-primary": "#b0c6ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      boxShadow: {
        float: "0px 20px 40px rgba(19,27,46,0.06)",
      },
    },
  },
  plugins: [],
}

export default config
