"""Add contact_messages for email tracking

Revision ID: 733adcb9c3f1
Revises: 6e952814e506
Create Date: 2026-04-08 21:26:25.326583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '733adcb9c3f1'
down_revision: Union[str, Sequence[str], None] = '6e952814e506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('venture', sa.String(length=50), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body_snippet', sa.Text(), nullable=True),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_messages_contact_id'), 'contact_messages', ['contact_id'], unique=False)
    op.create_index(op.f('ix_contact_messages_message_type'), 'contact_messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_contact_messages_venture'), 'contact_messages', ['venture'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_messages_venture'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_message_type'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_contact_id'), table_name='contact_messages')
    op.drop_table('contact_messages')
    # ### end Alembic commands ###
