"""Add advisory and roadmap tables

Revision ID: a21657c8a73f
Revises: b1c2d3e4f5a6
Create Date: 2026-04-06 16:20:20.205472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a21657c8a73f'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('effort_score', sa.SmallInteger(), nullable=True),
    sa.Column('margin_potential', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.Enum('backlog', 'in_progress', 'completed', name='roadmap_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_status'), 'roadmap', ['status'], unique=False)
    op.create_table('advisory_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('advisor_id', sa.Enum('architect', 'marketing', 'product', 'executive', name='advisor_id_enum'), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending_review', 'approved', 'rejected', 'archived', name='proposal_status_enum'), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisory_proposals_advisor_id'), 'advisory_proposals', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_advisory_proposals_job_id'), 'advisory_proposals', ['job_id'], unique=False)
    op.create_index(op.f('ix_advisory_proposals_status'), 'advisory_proposals', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advisory_proposals_status'), table_name='advisory_proposals')
    op.drop_index(op.f('ix_advisory_proposals_job_id'), table_name='advisory_proposals')
    op.drop_index(op.f('ix_advisory_proposals_advisor_id'), table_name='advisory_proposals')
    op.drop_table('advisory_proposals')
    op.drop_index(op.f('ix_roadmap_status'), table_name='roadmap')
    op.drop_table('roadmap')
    # ### end Alembic commands ###
