"""add accessibility audits table

Revision ID: a7eb62fd41b3
Revises: a21657c8a73f
Create Date: 2026-04-07 09:34:42.624097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7eb62fd41b3'
down_revision: Union[str, Sequence[str], None] = 'a21657c8a73f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessibility_audits',
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('raw_axe_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('roadmap_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('compliance_score', sa.Integer(), nullable=True),
    sa.Column('manual_override_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_accessibility_audits_job_id'), 'accessibility_audits', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accessibility_audits_job_id'), table_name='accessibility_audits')
    op.drop_table('accessibility_audits')
    # ### end Alembic commands ###
