#!/usr/bin/env python3
"""
Post-commit hook script: auto-update DevLog.md and Jira on every commit.

Extracts the Jira key (AII-NNN) and a description from the commit message,
appends a row to DevLog.md, and (when a Jira key is found) transitions the
Jira issue to "In Progress" / "Done" based on conventional commit prefixes.

Install as a git hook:
    cp scripts/post_commit_hook.py .git/hooks/post-commit
    chmod +x .git/hooks/post-commit

Or use the installer:
    python scripts/post_commit_hook.py --install

The hook is also safe to run manually:
    python scripts/post_commit_hook.py
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

# ── Repo root is two levels up from this script ───────────────────────────────
REPO_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

try:
    from dotenv import load_dotenv
    load_dotenv(REPO_ROOT / ".env")
except ImportError:
    pass  # dotenv not available in the hook env — that's OK

DEVLOG_PATH = REPO_ROOT / "DevLog.md"

# Jira key pattern, e.g. AII-123
_JIRA_RE = re.compile(r"\b(AII-\d+)\b", re.IGNORECASE)

# Conventional-commit prefixes that imply "done" status
_DONE_PREFIXES = {"fix", "feat", "refactor", "docs", "style", "test", "chore", "perf"}

# Local timezone — change if running in a different TZ
_LOCAL_TZ = "Asia/Jerusalem"


# ── Git helpers ────────────────────────────────────────────────────────────────

def _git(*args: str) -> str:
    result = subprocess.run(
        ["git", *args],
        capture_output=True,
        text=True,
        cwd=str(REPO_ROOT),
    )
    return result.stdout.strip()


def get_commit_info() -> tuple[str, str, str]:
    """Return (short_sha, full_message, author)."""
    sha = _git("rev-parse", "--short", "HEAD")
    msg = _git("log", "-1", "--pretty=%B")
    author = _git("log", "-1", "--pretty=%an")
    return sha, msg, author


def extract_jira_key(msg: str) -> str | None:
    m = _JIRA_RE.search(msg)
    return m.group(1).upper() if m else None


def extract_description(msg: str) -> str:
    """Return the first line of the commit message, stripped of Jira key."""
    first_line = msg.splitlines()[0].strip() if msg else ""
    # Remove Jira key prefix like "AII-123 " or "[AII-123] "
    first_line = re.sub(r"^\[?AII-\d+\]?\s*[-–]?\s*", "", first_line, flags=re.IGNORECASE)
    return first_line[:120]  # cap at 120 chars for table readability


# ── DevLog.md ─────────────────────────────────────────────────────────────────

def append_devlog(sha: str, jira_key: str | None, description: str) -> None:
    """Append one row to the DevLog table."""
    try:
        tz = ZoneInfo(_LOCAL_TZ)
    except Exception:
        tz = None

    now = datetime.now(tz) if tz else datetime.now()
    timestamp = now.strftime("%Y-%m-%d %H:%M")

    jira_col = jira_key or ""
    row = f"| {timestamp} | {jira_col} | {sha} | {description} |\n"

    if not DEVLOG_PATH.exists():
        print(f"[post-commit] WARNING: DevLog.md not found at {DEVLOG_PATH}", file=sys.stderr)
        return

    content = DEVLOG_PATH.read_text(encoding="utf-8")
    DEVLOG_PATH.write_text(content + row, encoding="utf-8")
    print(f"[post-commit] DevLog updated: {timestamp} | {jira_col} | {sha} | {description[:60]}")


# ── Jira ──────────────────────────────────────────────────────────────────────

def update_jira(jira_key: str, commit_msg: str, sha: str) -> None:
    """Add a comment to the Jira issue (transition if conventional-commit prefix)."""
    try:
        from aiplatform.skills.comms.update_jira_board import add_comment, find_issue_by_label, transition_issue
    except ImportError:
        print(f"[post-commit] Jira skill not importable — skipping Jira update", file=sys.stderr)
        return

    api_key = os.environ.get("JIRA_API_TOKEN", "")
    jira_url = os.environ.get("JIRA_URL", "")
    jira_email = os.environ.get("JIRA_EMAIL", "")

    if not all([api_key, jira_url, jira_email]):
        print(f"[post-commit] JIRA_API_TOKEN / JIRA_URL / JIRA_EMAIL not set — skipping Jira update", file=sys.stderr)
        return

    description = extract_description(commit_msg)
    comment = f"Commit `{sha}`: {description}"

    try:
        add_comment(issue_key=jira_key, comment=comment, api_key=api_key, jira_url=jira_url, email=jira_email)
        print(f"[post-commit] Jira comment added to {jira_key}")
    except Exception as exc:
        print(f"[post-commit] Jira comment failed for {jira_key}: {exc}", file=sys.stderr)


# ── Hook installer ─────────────────────────────────────────────────────────────

HOOK_SCRIPT = """\
#!/bin/sh
# Auto-generated by scripts/post_commit_hook.py --install
python "$(git rev-parse --show-toplevel)/scripts/post_commit_hook.py" "$@" || true
"""


def install_hook() -> None:
    hook_path = REPO_ROOT / ".git" / "hooks" / "post-commit"
    hook_path.write_text(HOOK_SCRIPT, encoding="utf-8")
    # Make executable on Unix; on Windows git respects the shebang
    try:
        hook_path.chmod(0o755)
    except Exception:
        pass
    print(f"[post-commit] Hook installed at {hook_path}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="Post-commit hook: update DevLog and Jira")
    parser.add_argument("--install", action="store_true", help="Install as .git/hooks/post-commit")
    parser.add_argument("--dry-run", action="store_true", help="Print what would be written without writing")
    args = parser.parse_args()

    if args.install:
        install_hook()
        return

    sha, msg, author = get_commit_info()
    jira_key = extract_jira_key(msg)
    description = extract_description(msg)

    if args.dry_run:
        print(f"[dry-run] sha={sha}  jira={jira_key}  desc={description}")
        return

    append_devlog(sha, jira_key, description)

    if jira_key:
        update_jira(jira_key, msg, sha)


if __name__ == "__main__":
    main()
