"""
Sprint 1 script — Bootstrap Google Drive folder structure for the Etsy shop.

Creates the full /EtsyShop/ hierarchy and writes all folder IDs to
drive_folder_ids.txt. Copy those IDs into .env after running.

Usage:
    python scripts/setup_drive_folders.py

Prerequisites:
    - google_credentials.json in project root (service account)
    - GOOGLE_DRIVE_ROOT_FOLDER_ID set in .env (the pre-shared /EtsyShop/ folder)
      OR omit to create /EtsyShop/ as a new top-level Drive folder.

After running:
    - Open drive_folder_ids.txt
    - Copy each DRIVE_*_ID value into your .env file
"""

import os
import sys
from pathlib import Path

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from dotenv import load_dotenv
from google.oauth2 import service_account
from googleapiclient.discovery import build

load_dotenv()

SCOPES = ["https://www.googleapis.com/auth/drive"]
CREDS_PATH = os.environ.get("GOOGLE_CREDENTIALS_PATH", "./google_credentials.json")
ROOT_FOLDER_ID = (os.environ.get("GOOGLE_DRIVE_ROOT_FOLDER_ID") or "").strip().lstrip("=") or None

# Folder hierarchy: (env_key, display_name, parent_env_key | None)
# parent_env_key=None means it hangs directly off the root
FOLDER_SPEC = [
    # (env_var_key,              display_name,     parent_env_key)
    ("DRIVE_ROOT",               "EtsyShop",       None),
    ("DRIVE_01_RESEARCH_ID",     "01-research",    "DRIVE_ROOT"),
    ("DRIVE_02_SUBJECTS_ID",     "02-subjects",    "DRIVE_ROOT"),
    ("DRIVE_03_IMAGES_ID",       "03-images",      "DRIVE_ROOT"),
    ("DRIVE_04_PACKAGES_ID",     "04-packages",    "DRIVE_ROOT"),
    ("DRIVE_05_REVIEW_ID",       "05-review",      "DRIVE_ROOT"),
    ("DRIVE_05_REVIEW_PENDING_ID",  "pending",     "DRIVE_05_REVIEW_ID"),
    ("DRIVE_05_REVIEW_APPROVED_ID", "approved",    "DRIVE_05_REVIEW_ID"),
    ("DRIVE_05_REVIEW_REJECTED_ID", "rejected",    "DRIVE_05_REVIEW_ID"),
    ("DRIVE_06_AUDIT_ID",        "06-audit",       "DRIVE_ROOT"),
    ("DRIVE_06_AUDIT_DRAFTS_ID", "drafts",         "DRIVE_06_AUDIT_ID"),
    ("DRIVE_06_AUDIT_PUBLISHED_ID", "published",   "DRIVE_06_AUDIT_ID"),
    ("DRIVE_07_PROMO_ID",        "07-promo",       "DRIVE_ROOT"),
]


def get_service():
    if not Path(CREDS_PATH).exists():
        print(f"ERROR: Service account credentials not found at '{CREDS_PATH}'")
        print("Download your service account JSON from Google Cloud Console.")
        sys.exit(1)
    creds = service_account.Credentials.from_service_account_file(CREDS_PATH, scopes=SCOPES)
    return build("drive", "v3", credentials=creds, cache_discovery=False)


def create_folder(service, name: str, parent_id: str) -> str:
    """Create a Drive folder and return its ID."""
    body = {
        "name": name,
        "mimeType": "application/vnd.google-apps.folder",
        "parents": [parent_id],
    }
    folder = service.files().create(body=body, fields="id,name").execute()
    return folder["id"]


def main():
    service = get_service()
    folder_ids: dict[str, str] = {}

    # Handle root folder
    root_key, root_name, _ = FOLDER_SPEC[0]
    if ROOT_FOLDER_ID:
        print(f"Using existing root folder: {ROOT_FOLDER_ID}")
        folder_ids[root_key] = ROOT_FOLDER_ID
    else:
        print(f"Creating root folder '{root_name}' in My Drive...")
        # Create in My Drive (no parent) — share with service account afterwards
        body = {
            "name": root_name,
            "mimeType": "application/vnd.google-apps.folder",
        }
        folder = service.files().create(body=body, fields="id,name,webViewLink").execute()
        folder_ids[root_key] = folder["id"]
        print(f"  Created: {folder['webViewLink']}")
        print(f"  ACTION REQUIRED: Share this folder with your service account email (Editor access).")
        print(f"  Service account: check '{CREDS_PATH}' → client_email field\n")

    # Create all subfolders
    for env_key, display_name, parent_key in FOLDER_SPEC[1:]:
        parent_id = folder_ids[parent_key]
        print(f"Creating '{display_name}'...")
        folder_id = create_folder(service, display_name, parent_id)
        folder_ids[env_key] = folder_id
        print(f"  ID: {folder_id}")

    # Write to drive_folder_ids.txt
    output_lines = [
        "# Google Drive folder IDs — generated by scripts/setup_drive_folders.py",
        "# Copy these into your .env file\n",
    ]
    for env_key, folder_id in folder_ids.items():
        output_lines.append(f"{env_key}={folder_id}")

    output_path = Path("drive_folder_ids.txt")
    output_path.write_text("\n".join(output_lines))

    print(f"\nDone. Folder IDs written to: {output_path.resolve()}")
    print("Next step: copy those values into your .env file.")


if __name__ == "__main__":
    main()
